// app.js - purple flex interactions (no external assets)
// helpers
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));

// set year
document.getElementById('year').textContent = new Date().getFullYear();

// preloader hide
window.addEventListener('load', ()=>{
  const pre = document.getElementById('preloader');
  if(pre){ pre.style.opacity = 0; setTimeout(()=>pre.remove(), 600); }
});

// particles generator (dom dots)
(function particles(){
  const root = document.getElementById('particles');
  if(!root) return;
  const colors = ['#9b59b6','#b57af8','#8e44ad','#cfa8ff'];
  const N = 80;
  for(let i=0;i<N;i++){
    const el = document.createElement('div');
    el.className = 'p-dot';
    const size = 2 + Math.random()*6;
    el.style.width = el.style.height = size + 'px';
    el.style.left = (Math.random()*120 - 10) + 'vw';
    el.style.top = (Math.random()*120 - 10) + 'vh';
    el.style.background = colors[Math.floor(Math.random()*colors.length)];
    el.style.opacity = (0.2 + Math.random()*0.9).toFixed(2);
    el.style.animationDuration = (6 + Math.random()*12) + 's';
    el.style.animationDelay = (-Math.random()*10) + 's';
    root.appendChild(el);
  }
})();

// keyboard accessibility: skip to main with "s"
document.addEventListener('keydown', (e)=>{
  if(e.key === 's'){ const m = document.querySelector('main'); if(m) m.scrollIntoView({behavior:'smooth'}); }
});

// simple scroll reveal
(function reveal(){
  const els = $$('.panel, .card, .section-title, .link-pill');
  els.forEach(el=>{ el.style.opacity = 0; el.style.transform = 'translateY(14px)'; el.style.transition = 'all .7s cubic-bezier(.16,.8,.24,1)'; });
  function onScroll(){ const top = window.scrollY + window.innerHeight; els.forEach(el=>{ if(el.getBoundingClientRect().top + window.scrollY < top - 80){ el.style.opacity = 1; el.style.transform = 'translateY(0)'; } }); }
  window.addEventListener('scroll', onScroll);
  window.addEventListener('load', onScroll);
})();

// inject dot styles
(function injectStyles(){
  const css = `.p-dot{position:fixed;border-radius:50%;box-shadow:0 0 12px rgba(140,40,180,.6);animation:pd 10s linear infinite}@keyframes pd{0%{transform:translateY(0)}100%{transform:translateY(-120vh) scale(.4)}}`;
  const s = document.createElement('style'); s.textContent = css; document.head.appendChild(s);
})();

console.log('purple flex loaded — press "s" to skip to main');

// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
// filler js line - purple template
